name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: spir-ingest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PORT: 5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: '17'
          cache: maven

      - name: Build and test
        run: mvn -B --update-snapshots verify -DargLine="-Dspring.datasource.url=jdbc:postgresql://localhost:5432/database" -DargLine="-Dspring.datasource.username=postgres" -DargLine="-Dspring.datasource.password=postgres"
